repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --check-only .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: poetry run black --check .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false

      - id: ut
        name: unit tests
        entry: poetry run pytest tests/unit/
        language: system
        types: [python]
        pass_filenames: false

      - id: it
        name: integration tests
        entry: make itests
        language: system
        types: [python]
        pass_filenames: false
