version: '3.7'

services:
  elastic:
    image: elasticsearch:7.10.1
    hostname: elastic
    container_name: elastic
    ports:
      - 9200:${ELASTIC_PORT}
    env_file:
      - ./tlparser/env/development/.env.dev.elastic
    volumes:
      - ./tlparser/data/dev/elastic:/var/lib/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://elastic:${ELASTIC_PORT} >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      back-dev:
        ipv4_address: 192.168.10.7
    restart: always

  kibana:
    image: kibana:7.10.1
    hostname: kibana
    container_name: kibana
    ports:
      - 5601:${KIBANA_PORT}
    env_file:
      - ./tlparser/env/development/.env.dev.elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://kibana:${KIBANA_PORT} >/dev/null || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      back-dev:
        ipv4_address: 192.168.10.8
    links:
      - elastic
    depends_on:
      elastic:
        condition: service_healthy
    restart: always