version: '3.7'

services:
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - 8081:${MONGO_PORT}
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always